### ISSUE TITLE
Student Page (Listing)

### ISSUE THREAD

**Issue by westbrookdaniel** [FrancisVillarba/2020-Curtin-DPD-GradShow#15]
Develop the basic outline for the student page including fully responsive.

Based on the wireframes pinned in the coding chat.

Don't worry about implementing complex searching or functionality.

**Comment by FrancisVillarbaLegacy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Merge James' code after investigating the double refresh bug](https://trello.com/c/XuTabs2k/45-merge-james-code-after-investigating-the-double-refresh-bug)
