### ISSUE TITLE
Student Data System

### ISSUE THREAD

**Issue by westbrookdaniel** [FrancisVillarba/2020-Curtin-DPD-GradShow#18]
Setting up the system for gathering student data and getting it onto the pages. 
Possibly an API?

Discuss before implementing

**Comment by FrancisVillarbaLegacy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backend Student Data System](https://trello.com/c/XRtO5sB2/33-backend-student-data-system)

**Comment by FrancisVillarbaLegacy** [comment]
https://www.11ty.dev/docs/quicktips/eliminate-js/

**Comment by FrancisVillarbaLegacy** [comment]
https://firebase.google.com/products/firestore?authuser=1

**Comment by FrancisVillarbaLegacy** [comment]
https://firebase.google.com/products/storage

For block storage...?

**Comment by FrancisVillarbaLegacy** [comment]
Now working on this enhancement issue using the branch 'Student-data-system'

**Comment by FrancisVillarbaLegacy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backend Student Data System](https://trello.com/c/XRtO5sB2/33-backend-student-data-system)

**Comment by FrancisVillarbaLegacy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backend Student Data System V2](https://trello.com/c/af4aqTY2/36-backend-student-data-system-v2)
