### ISSUE TITLE
Lazy Loading Images 11ty Plugin

### ISSUE THREAD

**Issue by westbrookdaniel** [FrancisVillarba/2020-Curtin-DPD-GradShow#6]
Lazy loading images to improve performance in the future.

Just need this plugin for 11ty installed and integrated.
https://github.com/liamfiddler/eleventy-plugin-lazyimages/

**Comment by FrancisVillarbaLegacy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Lazy Load for Images](https://trello.com/c/thWS5Tfi/25-add-lazy-load-for-images)

**Comment by westbrookdaniel** [comment]
Not going to work due to how we dynamically insert most of our images
